# Generated by Django 5.2.7 on 2026-02-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_commande_code_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='lieu_livraison',
            field=models.CharField(default='Yamoussoukro', editable=False, max_length=250),
        ),
    ]
