# Generated by Django 5.2.7 on 2026-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0011_zonelivraison_commande_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude_client',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
