# Generated by Django 5.2.7 on 2026-02-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_client_utilisateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="is_active",
        ),
    ]
