# Generated by Django 5.2.7 on 2026-03-08 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0029_alter_alertproduit_produit_and_more"),
        ("recommandations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommandation",
            name="produit_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommandations_source",
                to="produits.produit",
            ),
        ),
    ]
