# Generated by Django 5.2.7 on 2026-02-05 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0016_alter_produit_categorie_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.categorie'),
        ),
    ]
