# Generated by Django 5.2.7 on 2026-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0017_alter_produit_categorie_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='caracteristiques_produit',
            field=models.TextField(blank=True, null=True, verbose_name='caracteristiques du produit'),
        ),
    ]
