# Generated by Django 5.2.7 on 2026-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0019_alter_produit_caracteristiques_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='caracteristiques_produit',
            field=models.TextField(blank=True, null=True, verbose_name='caracteristiques du produit (Ex: Ecran, Clavier, Souris)'),
        ),
    ]
