# Generated by Django 5.2.7 on 2026-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0023_alter_produit_image_produit_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='caracteristiques_produit',
            field=models.TextField(blank=True, null=True, verbose_name='caractéristiques du produit (Ex: Écran, Clavier, Souris)'),
        ),
    ]
