# Generated by Django 5.2.7 on 2026-02-26 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0024_alter_produit_caracteristiques_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='note_produit',
            field=models.CharField(choices=[('0', '0 étoile'), ('1', '1 étoile'), ('2', '2 étoiles'), ('3', '3 étoiles'), ('4', '4 étoiles'), ('5', '5 étoiles')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='produit',
            name='pourcentage_promo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_promo_produit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
