# Generated by Django 5.2.7 on 2026-02-26 12:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0027_alter_categorie_pourcentage_promo_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='note_produit',
        ),
        migrations.CreateModel(
            name='NotationProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_notation', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note_produit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note du produit (de 0 à 5 étoiles)')),
                ('date_notation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations_produit', to='produits.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('produit', 'utilisateur')},
            },
        ),
    ]
