# Generated by Django 5.2.7 on 2026-03-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0030_alertproduit_produits_al_produit_2a56c6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
