# Generated by Django 5.2.7 on 2026-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produits", "0031_produit_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
